name: LinkedIn Auto Post

on:
  schedule:
    - cron: "30 5 * * *"  # Daily at 11:00 AM IST
  workflow_dispatch:

jobs:
  linkedin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run LinkedIn Post
        env:
          PERPLEXITY_API_KEY: ${{ secrets.PERPLEXITY_API_KEY }}
          LINKEDIN_ACCESS_TOKEN: ${{ secrets.LINKEDIN_ACCESS_TOKEN }}
          LINKEDIN_USER_URN: ${{ secrets.LINKEDIN_USER_URN }}
        run: python app/linkedin_client.py